### ISSUE TITLE
在编译的最后出现了一个错误

### ISSUE THREAD

**Issue by theside9** [EndCredits/android_kernel_xiaomi_sm8350#2]
编译内核的过程很顺利，但是结束后，提示缺少vendor_dlkm.img，报错如下：
Kernel Build Costed 26min 16s
cp: cannot stat '/srv/media/WD/pe/out/target/product/renoir/obj/PACKAGING/target_files_intermediates/aosp_renoir-target_files-eng.credits/IMAGES//vendor_dlkm.img': No such file or directory
------------------------------
 Generating Flashable Kernel
------------------------------
 Removing old package file
 Getting AnyKernel
 Copying Kernel File
cp: cannot stat 'vendor_dlkm.img': No such file or directory
find: ‘vendor_dlkm/’: No such file or directory
find: ‘vendor_dlkm/’: No such file or directory
find: ‘vendor_dlkm/’: No such file or directory
find: ‘vendor_dlkm/’: No such file or directory
find: ‘vendor_dlkm/’: No such file or directory
 Packaging flashable Kernel
 Target File:  ../out/./ak3/Kernel-20230529-1508-5.4.233.zip

出现这个是否会影响内核开机？我刚刚使用magiskboot将编译out目录下的Image，打包到了开发版卡刷包的boot.img中，并使用fastboot boot boot.img来测试启动，但是在出现mi加载后，黑屏了，不清楚是否是这个报错引起的？

**Comment by EndCredits** [comment]
首先该内核并不支持 MIUI ( 请查阅 #1 )，请不要在 MIUI 上使用，此外， renoir 是 GKI 1.0 设备，无法保证 KMI 稳定性，又由于内核已合并上游更改，内核模块验证无法通过，将导致模块无法加载，进而导致开机黑屏

以下是该 issue 可能的解决方案

1. 更换使用该内核的类原生，该方案可以不需要手动编译内核，但如果您对 MIUI 有刚需则该方案并不适用
2. 查阅 [tanz3/android_kernel_xiaomi_sm8350-miui](https://github.com/tanz3/kernel_xiaomi_sm8350-miui)，该内核支持 MIUI，您可以查阅该内核的提交记录并择优拣选提交记录中与 MIUI 相关的部分，并内联所有内核模块 ( 可以查阅 feat-inline 分支 )，并合并至本内核中，然后重新编译，并使用 magiskboot 重新打包镜像
3. 查阅 [tanz3/android_kernel_xiaomi_sm8350-miui](https://github.com/tanz3/kernel_xiaomi_sm8350-miui)，并基于该内核中的 defconfig 为 renoir 重做一份 defconfig 并编译刷入

关于 vendor_dlkm.img，这个报错源自于一次失败的尝试，MIUI 并没有使用 vendor_dlkm 分区，所以为 MIUI 编译时该错误可忽略

**Comment by theside9** [comment]
刚接触内核编译，谢谢您的解答，我去尝试一下您说得

**Comment by theside9** [comment]
您好，我尝试使用了您的PixelExperience_plus ROM，在使用lsxposed的时候，提示kernelsu版本低，于是我再次使用该项目同步了最新的kernelsu，编译了内核。好消息是，它能正常启动并进入系统，但是在锁屏界面，触控似乎失效了。我合并boot.img的方法依旧是将编译好的Image使用magiskboot repack，是缺少了什么驱动么？

**Comment by EndCredits** [comment]
其实跟 MIUI 开不了机原理差不多，也是 magic 改变了，模块验证过不了，所以其余模块无法加载，应该不只是触控，像 wlan 等功能应该都没法用。目前除了在 AOSP 源码里生成 vendor_boot 和 vendor_dlkm 之外我还没有发现什么好的方法可以一并更新类原生的内核模块

有个朋友想维护 renoir 的 PixelExperience ，我就让给他了，所以我现在不再维护 PixelExperience 了，您也可以自己尝试编译 PixelExperience ，也可以尝试 DerpFest，同样有全量 GMS ，支持换图标以及其他一系列自定义，截至本 comment 回复前，最新版本是

https://mirrors.crepuscular-aosp.icu/ROMs/renoir/DerpFest-20230527

**Comment by EndCredits** [comment]
GKI 1.0 设备简直孤儿... 如果有钱的话还是建议换 GKI 2.0 设备吧，那些设备的 GKI 就很舒服了，没这么阴间，可以直接刷 weishu 大佬的 action 提供的镜像。这 GKI 1.0 说是 Generic ，其实根本不 Generic，咱这也不是完全的 GKI，而是 QGKI ，也就是高通 fork 的 GKI，反正就很阴间

**Comment by theside9** [comment]
确实挺阴间的，看来还是钞能力好使hhh
