### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by MYSK-QC** [EndCredits/android_kernel_xiaomi_sm8350#3]
编译haydn内核报错，请问如何解决![Screenshot_2023-09-03-07-16-34-620_com.microsoft.emmx.jpg](https://github.com/EndCredits/android_kernel_xiaomi_sm8350/assets/68981944/13226496-fc4a-4cb8-afd1-270ac1964d86)

**Comment by EndCredits** [comment]
MIUI 不能用，你要放弃吗？

---------

MIUI can't work with this kernel. Do you want to give up?

**Comment by MYSK-QC** [comment]
> MIUI 不能用，你要放弃吗？
> 
> ---------
> 
> MIUI can't work with this kernel. Do you want to give up?

用不了？额，好不容易找到一个竟然miui用不了

**Comment by MYSK-QC** [comment]
有没有miui可以用的源码

**Comment by ianchb** [comment]
> 有没有miui可以用的源码

try this:
https://github.com/tanz3/kernel_xiaomi_sm8350-miui
